#!/usr/bin/env python3
# =============================================================================
# ONCOSIEVE — pan-cancer variant curation and rescue tool
# Parser: Cancer Hotspots (GRCh38, MANE Select)
#
# Author : Dr Christopher Trethewey
# Email  : christopher.trethewey@nhs.net
# =============================================================================

"""
parse_hotspots.py
Parse CancerHotspots V1/V2/V3 data remapped to GRCh38 MANE Select coordinates.

Required file (generated by hotspots_vep_remap.py):
  data/hotspots/hotspots_grch38_mane.tsv

This replaces the previous API-based parser which returned protein-level data
only with no usable genomic coordinates.
"""

import os

import pandas as pd

from parsers.common import (
    STANDARD_COLS,
    clean_allele,
    empty_standard_df,
    is_valid_allele,
    map_consequence,
    normalise_chrom,
    setup_logger,
)

log = setup_logger('CancerHotspots')


def parse_hotspots(tsv_path: str,
                   max_qvalue: float = 0.05) -> pd.DataFrame:
    """
    Parse the pre-remapped CancerHotspots GRCh38 MANE Select TSV.

    Parameters
    ----------
    tsv_path  : path to hotspots_grch38_mane.tsv (output of hotspots_vep_remap.py)
    max_qvalue: q-value significance threshold (default 0.05)

    Returns
    -------
    DataFrame with STANDARD_COLS schema.
    """
    if not os.path.exists(tsv_path):
        log.warning('CancerHotspots TSV not found: %s — skipping', tsv_path)
        log.warning('Run hotspots_vep_remap.py to generate this file.')
        return empty_standard_df()

    log.info('Parsing CancerHotspots GRCh38 MANE Select TSV: %s', tsv_path)

    try:
        df = pd.read_csv(tsv_path, sep='\t', dtype=str, low_memory=False)
    except Exception as e:
        log.error('Failed to read hotspots TSV: %s', e)
        return empty_standard_df()

    rows = []
    n_skipped_qvalue = 0
    n_skipped_allele = 0

    for _, row in df.iterrows():
        # q-value filter
        try:
            qval = float(row.get('qvalue', 1.0) or 1.0)
        except (ValueError, TypeError):
            qval = 1.0
        if qval > max_qvalue:
            n_skipped_qvalue += 1
            continue

        chrom = normalise_chrom(str(row.get('chrom', '') or ''))
        ref   = clean_allele(str(row.get('ref', '') or ''))
        alt   = clean_allele(str(row.get('alt', '') or ''))

        if not is_valid_allele(ref) or not is_valid_allele(alt):
            n_skipped_allele += 1
            continue

        try:
            pos = int(float(str(row.get('pos', 0))))
        except (ValueError, TypeError):
            n_skipped_allele += 1
            continue

        try:
            n_samples = int(float(str(row.get('n_samples', 0) or 0)))
        except (ValueError, TypeError):
            n_samples = 0

        rows.append({
            'chrom':       chrom,
            'pos':         pos,
            'ref':         ref,
            'alt':         alt,
            'gene':        str(row.get('gene', '') or '').strip(),
            'hgvsc':       str(row.get('hgvsc', '') or '').strip(),
            'hgvsp':       str(row.get('hgvsp', '') or '').strip(),
            'consequence': map_consequence(str(row.get('consequence', 'unknown') or 'unknown').strip()),
            'cancer_type': 'pan_cancer',
            'n_samples':   n_samples,
            'source':      'CancerHotspots',
        })

    log.info(
        'CancerHotspots: %d rows kept | %d excluded by q-value | %d excluded by invalid allele',
        len(rows), n_skipped_qvalue, n_skipped_allele
    )

    if not rows:
        log.warning('CancerHotspots: no rows produced — check TSV and q-value threshold')
        return empty_standard_df()

    return pd.DataFrame(rows, columns=STANDARD_COLS)
