#!/usr/bin/env python3
# =============================================================================
# ONCOSIEVE — pan-cancer variant curation and rescue tool
# Parser: Cancer Hotspots (GRCh38, MANE Select)
#
# Author : Dr Christopher Trethewey
# Email  : christopher.trethewey@nhs.net
# =============================================================================

"""
parse_hotspots.py
Parse CancerHotspots V1/V2/V3 data remapped to GRCh38 MANE Select coordinates.

Required file (generated by hotspots_vep_remap.py):
  data/hotspots/hotspots_grch38_mane.tsv

This replaces the previous API-based parser which returned protein-level data
only with no usable genomic coordinates.
"""

import os

import pandas as pd

from parsers.common import (
    STANDARD_COLS,
    empty_standard_df,
    setup_logger,
)

log = setup_logger('CancerHotspots')


def parse_hotspots(tsv_path: str,
                   max_qvalue: float = 0.05) -> pd.DataFrame:
    """
    Parse the pre-remapped CancerHotspots GRCh38 MANE Select TSV.

    Parameters
    ----------
    tsv_path  : path to hotspots_grch38_mane.tsv (output of hotspots_vep_remap.py)
    max_qvalue: q-value significance threshold (default 0.05)

    Returns
    -------
    DataFrame with STANDARD_COLS schema.
    """
    if not os.path.exists(tsv_path):
        log.warning('CancerHotspots TSV not found: %s — skipping', tsv_path)
        log.warning('Run hotspots_vep_remap.py to generate this file.')
        return empty_standard_df()

    log.info('Parsing CancerHotspots GRCh38 MANE Select TSV: %s', tsv_path)

    try:
        df = pd.read_csv(tsv_path, sep='\t', dtype=str, low_memory=False)
    except Exception as e:
        log.error('Failed to read hotspots TSV: %s', e)
        return empty_standard_df()

    from parsers.common import CONSEQUENCE_MAP

    # Vectorized processing
    # q-value filter
    df['qvalue'] = pd.to_numeric(df.get('qvalue', pd.Series(dtype=float)), errors='coerce').fillna(1.0)
    n_before = len(df)
    df = df[df['qvalue'] <= max_qvalue].copy()
    n_skipped_qvalue = n_before - len(df)

    # Clean alleles
    df['ref'] = df['ref'].fillna('').str.strip().str.upper()
    df['alt'] = df['alt'].fillna('').str.strip().str.upper()

    # Filter invalid alleles
    valid_re = r'^[ACGTNacgtn*\-]+$'
    valid_mask = df['ref'].str.match(valid_re, na=False) & df['alt'].str.match(valid_re, na=False)
    n_skipped_allele = (~valid_mask).sum()
    df = df[valid_mask].copy()

    # Normalise chromosome
    raw_chrom = df['chrom'].fillna('').str.strip().str.replace(r'^chr', '', regex=True)
    raw_chrom = raw_chrom.replace({'MT': 'M', 'mt': 'M'})
    df['chrom'] = 'chr' + raw_chrom

    # Position and samples
    df['pos'] = pd.to_numeric(df['pos'], errors='coerce')
    df = df.dropna(subset=['pos'])
    df['pos'] = df['pos'].astype(int)
    df['n_samples'] = pd.to_numeric(df.get('n_samples', 0), errors='coerce').fillna(0).astype(int)

    # String columns
    for col in ('gene', 'hgvsc', 'hgvsp'):
        if col in df.columns:
            df[col] = df[col].fillna('').str.strip()
        else:
            df[col] = ''

    # Consequence mapping
    if 'consequence' in df.columns:
        df['consequence'] = df['consequence'].fillna('unknown').str.strip().map(CONSEQUENCE_MAP).fillna('other')
    else:
        df['consequence'] = 'unknown'

    df['cancer_type'] = 'pan_cancer'
    df['source'] = 'CancerHotspots'

    log.info(
        'CancerHotspots: %d rows kept | %d excluded by q-value | %d excluded by invalid allele',
        len(df), n_skipped_qvalue, n_skipped_allele
    )

    if df.empty:
        log.warning('CancerHotspots: no rows produced — check TSV and q-value threshold')
        return empty_standard_df()

    for col in STANDARD_COLS:
        if col not in df.columns:
            df[col] = ''
    return df[STANDARD_COLS].reset_index(drop=True)
